name: t_store
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  cached_network_image: ^3.3.1
  capped_progress_indicator: ^0.0.2
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.15.10
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.4.1
  equatable: ^2.0.5
  firebase_auth: ^4.17.9
  firebase_core: ^2.27.1
  firebase_storage: ^11.6.10
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_facebook_auth: ^6.1.1
  flutter_native_splash: ^2.3.10
  flutter_rating_bar: ^4.0.1
  get_it: ^7.6.7
  get_storage: ^2.1.1
  google_sign_in: ^6.2.1
  http: ^1.2.1
  iconsax: ^0.0.8
  image_picker: ^1.0.8
  intl: ^0.19.0
  logger: ^2.0.2+1
  lottie: ^3.1.0
  readmore: ^2.2.0
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/animations/
    - assets/images/banners/
    - assets/images/products/
    - assets/images/reviews/
    - assets/images/on_boarding_images/
    - assets/images/content/
    - assets/icons/categories/
    - assets/icons/brands/
    - assets/icons/payment_methods/
    - assets/images/
    - assets/logos/
    - assets/screenshots/
  fonts:
    - family: Coolvetica
      fonts:
        - asset: assets/fonts/coolvetica_regular.otf
        - asset: assets/fonts/coolvetica_regular_italic.otf
          style: italic
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-LightItalic.ttf
          weight: 300
          style: italic
