default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
     sh "flutter clean"
     sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
     firebase_app_distribution(
       app: "1:636552914502:android:911ed43349808e438a8c47",
       firebase_cli_token: "1//03aLWRGFdoenPCgYIARAAGAMSNwF-L9Irv8IGxNp7pwaoWytQ05t4-ZdIGaE3e6kDGjEeN-pRGHpW7jlNzmxy3VccrjIqd_il_Iw",
       android_artifact_type: "APK",
       android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
       testers: "hmdy7486@gmail.com",
       release_notes: "The Fastlane App Distribution was released"
     )
   end
 end