 name: Android Fastlane with Firebase App Distribution Workflow
 
 on:
   push:
     branches:
       - mobile-app-stable # The branch that you would like to run the workflow when you push into it.
 
 jobs:
   distribute_to_firebase:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout my repo code
         uses: actions/checkout@v2
 
       - name: Set up JDK 17
         uses: actions/setup-java@v2
         with:
           java-version: "17"
           distribution: "temurin"
 
       - name: Install Flutter
         uses: subosito/flutter-action@v2
         with:
           channel: stable
 
       # If there was an error, then run this: "cd android" then "bundle lock --add-platform x86_64-linux"
       - name: Setup Ruby
         uses: ruby/setup-ruby@v1
         with:
           ruby-version: "3.3.5"
           bundler-cache: true
           working-directory: android
 
       - name: Build and Distribute App
         env:
           FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
         run: |
           bundle exec fastlane android firebase_distribution
         working-directory: android